//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public byte id { get; set; }
        public string contrasena { get; set; }
        public string email { get; set; }
        public string roles { get; set; }
        public Nullable<bool> activo { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<System.DateTime> ultimoCambioContrasena { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
    }
}
